In [5]:
import pandas as pd
import sqlite3
import os

In [9]:
def csv_to_sqlite(csv_path, db_name='catalog.db', table_name='user_catalog', if_exists='replace'):
    """
    Read a CSV file and store its contents in a SQLite table.
    
    Parameters:
    csv_path (str): Path to the CSV file.
    db_name (str): Name of the SQLite database file (default: 'catalog.db').
    table_name (str): Name of the table to create or replace (default: 'user_catalog').
    if_exists (str): Behavior if the table exists. Options: 'fail', 'replace', 'append' (default: 'replace').
    
    Returns:
    None
    """
    try:
        # Read the CSV file
        df = pd.read_csv(csv_path)
        print(f"Successfully read CSV file: {csv_path}")
        print(f"DataFrame shape: {df.shape}")
        
        # Connect to SQLite database (creates it if it doesn't exist)
        conn = sqlite3.connect(db_name)
        print(f"Connected to database: {db_name}")
        
        # Write the DataFrame to SQLite table
        df.to_sql(table_name, conn, if_exists=if_exists, index=False)
        print(f"Data inserted into table '{table_name}' with if_exists='{if_exists}'.")
        
        # Verify by reading back a few rows
        cursor = conn.cursor()
        cursor.execute(f"SELECT * FROM {table_name} LIMIT 3")
        rows = cursor.fetchall()
        print(f"First 3 rows from {table_name}:\n{rows}")
        
        # Close the connection
        conn.close()
        print("Database connection closed.")
    except FileNotFoundError:
        print(f"Error: The file {csv_path} was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

In [10]:
import requests\n
from typing import Union\n
\n
\n
def fetch_best_book_match(title: str, author: str) -> Union[dict, None]:\n
# Check if the file exists (optional)
if os.path.exists(csv_file_path):
    csv_to_sqlite(csv_file_path)
else:
    print(f"Please update the csv_file_path variable to point to your CSV file.\nCurrent path '{csv_file_path}' does not exist.")

Successfully read CSV file: goodreads-export-sample.csv
DataFrame shape: (8, 24)
Connected to database: catalog.db
Data inserted into table 'user_catalog' with if_exists='replace'.
First 3 rows from user_catalog:
[(58213401, "Mona's Eyes", 'Thomas Schlesser', 'Schlesser, Thomas', None, '="1643756033"', '="9781643756031"', 5, 4.32, 'Europa Editions', 'Hardcover', 354, 2025, 2024, '2026/09/27', '2026/09/20', 'favorites', 'favorites (#1)', 'read', None, None, None, 1, 0), (29184756, 'The Nightingale', 'Kristin Hannah', 'Hannah, Kristin', None, '="0312577222"', '="9780312577223"', 5, 4.57, "St. Martin's Press", 'Hardcover', 440, 2015, 2015, '2026/03/21', '2026/03/02', None, None, 'read', None, None, None, 1, 1), (37482910, 'How to Hide an Empire: A History of the Greater United States', 'Daniel Immerwahr', 'Immerwahr, Daniel', None, '="0374172146"', '="9780374172145"', 5, 4.34, 'Farrar, Straus and Giroux', 'Hardcover', 528, 2019, 2019, '2026/06/28', '2026/06/10', None, None, 'read', None, None, None, 1, 0)]
Database connection closed.

In [11]:
# Inspect the SQLite table: column names and first few rows
import sqlite3
import pandas as pd

conn = sqlite3.connect('catalog.db')

# Show column names
cursor = conn.cursor()
cursor.execute("PRAGMA table_info(user_catalog)")
columns = cursor.fetchall()
print("Column names:")
for col in columns:
    print(f"  [{col[0]}] {col[1]} ({col[2]})")

print()

# Preview first 5 rows as a DataFrame
df_preview = pd.read_sql_query("SELECT * FROM user_catalog LIMIT 5", conn)
conn.close()

df_preview

Column names:
  [0] Book Id (INTEGER)
  [1] Title (TEXT)
  [2] Author (TEXT)
  [3] Author l-f (TEXT)
  [4] Additional Authors (TEXT)
  [5] ISBN (TEXT)
  [6] ISBN13 (TEXT)
  [7] My Rating (INTEGER)
  [8] Average Rating (REAL)
  [9] Publisher (TEXT)
  [10] Binding (TEXT)
  [11] Number of Pages (INTEGER)
  [12] Year Published (INTEGER)
  [13] Original Publication Year (INTEGER)
  [14] Date Read (TEXT)
  [15] Date Added (TEXT)
  [16] Bookshelves (TEXT)
  [17] Bookshelves with positions (TEXT)
  [18] Exclusive Shelf (TEXT)
  [19] My Review (REAL)
  [20] Spoiler (REAL)
  [21] Private Notes (REAL)
  [22] Read Count (INTEGER)
  [23] Owned Copies (INTEGER)

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,...,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Owned Copies
0,58213401,Mona's Eyes,Thomas Schlesser,"Schlesser, Thomas",None,"=""1643756033""","=""9781643756031""",5,4.32,Europa Editions,...,2026/09/27,2026/09/20,favorites,favorites (#1),read,None,None,None,1,0
1,29184756,The Nightingale,Kristin Hannah,"Hannah, Kristin",None,"=""0312577222""","=""9780312577223""",5,4.57,St. Martin's Press,...,2026/03/21,2026/03/02,None,None,read,None,None,None,1,1
2,37482910,How to Hide an Empire: A History of the Greate...,Daniel Immerwahr,"Immerwahr, Daniel",None,"=""0374172146""","=""9780374172145""",5,4.34,"Farrar, Straus and Giroux",...,2026/06/28,2026/06/10,None,None,read,None,None,None,1,0
3,44829173,Lock Every Door,Riley Sager,"Sager, Riley",None,"=""1524745146""","=""9781524745141""",5,3.94,Dutton,...,2026/07/19,2026/07/05,None,None,read,None,None,None,1,0
4,51029384,Hooked,Asako Yuzuki,"Yuzuki, Asako",Polly Barton,"=""0063317008""","=""9780063317009""",4,3.88,HarperVia,...,2026/05/17,2026/05/01,None,None,read,None,None,None,1,0

In [21]:
import requests
import re
from typing import Union

# ── Priority Genres & Themes ─────────────────────────────────────────────────
PRIORITY_GENRES = [
    "historical fiction",
    "science fiction",
    "romance",
    "fantasy",
    "thriller",
    "mystery",
    "suspense",
    "crime",
    "horror",
    "adventure",
    "history",
    "biography",
    "autobiography",
    "memoir",
    "war",
    "family",
    "philosophy",
    "psychology",
    "politics",
    "drama",
    "poetry",
    "science",
    "art",
    "nonfiction",
]


def clean_and_prioritize_subjects(
    raw_subjects: list,
    places: list = None,
    times: list = None,
    limit: int = 5,
) -> list:
    """
    Filter, clean, and prioritize book subjects:
      1. Convert to lowercase & deduplicate (preserving order).
      2. Strip 'fiction / ' prefixes and deprioritize generic 'fiction'.
      3. Drop place and time tags.
      4. Prioritize specific genres & themes (historical fiction, fantasy, thriller, etc.).
      5. 'fiction' is placed at the end so it only serves as a fallback if no specific genre exists.
      6. Return up to limit clean subjects.
    """
    if not raw_subjects:
        return []

    places_set = {str(p).lower().strip() for p in (places or []) if p}
    times_set = {str(t).lower().strip() for t in (times or []) if t}

    time_regex = re.compile(
        r"((1\d{3}|20\d{2})s?|\d{1,2}(st|nd|rd|th)\s+century)",
        re.IGNORECASE,
    )

    seen = set()
    cleaned = []
    has_generic_fiction = False

    for item in raw_subjects:
        if not item or not isinstance(item, str):
            continue

        s = item.lower().strip()

        # Clean prefix like 'fiction / ' or 'fiction - '
        s = re.sub(r"^fiction\s*[/–—\-]\s*", "", s).strip()

        # Isolate generic 'fiction' or 'general'
        if s in ("fiction", "general", "general fiction"):
            has_generic_fiction = True
            continue

        # Drop anything containing ":"
        if ":" in s:
            continue

        # Drop library catalog URIs or fast / OCLC identifiers
        if "http" in s or "fast (" in s or "(ocolc)" in s:
            continue

        # Drop review / bestseller / marketing tags
        if "new york times" in s or "bestseller" in s:
            continue

        # Deduplicate
        if s in seen:
            continue
        seen.add(s)

        # Drop place and time tags
        if s in places_set or s in times_set:
            continue
        if "(imaginary place)" in s or "(place)" in s:
            continue
        if any(p in s for p in places_set if len(p) > 2) and (
            ", fiction" in s or "description and travel" in s
        ):
            continue
        if time_regex.search(s) and not any(kw in s for kw in ["war", "history"]):
            continue

        cleaned.append(s)

    tier1 = []
    tier2 = []
    tier3 = []

    for s in cleaned:
        if s in PRIORITY_GENRES:
            tier1.append(s)
        elif any(re.search(r"" + re.escape(g) + r"", s) for g in PRIORITY_GENRES):
            tier2.append(s)
        else:
            tier3.append(s)

    selected = []
    selected_words = set()

    for s in (tier1 + tier2 + tier3):
        words = set(re.findall(r"\w+", s))
        if len(words) > 1 and words.issubset(selected_words):
            continue
        selected.append(s)
        selected_words.update(words)
        if len(selected) >= limit:
            break

    # If no specific genres were found, fallback to 'fiction' if present
    if not selected and has_generic_fiction:
        selected.append("fiction")
    elif has_generic_fiction and len(selected) < limit:
        # Append generic fiction to the end so it never overrides specific genres as primary
        selected.append("fiction")

    return selected


def fetch_best_book_match(title: str, author: str) -> Union[dict, None]:
    """
    Query the Open Library Search API for a book by title and author.
    Returns the result with the most editions — i.e. the canonical work.
    Returns None if no results are found.
    """
    url = "https://openlibrary.org/search.json"
    params = {
        "title": title,
        "author": author,
        "limit": 3,
        "fields": ",".join([
            "key",
            "title",
            "author_name",
            "first_publish_year",
            "edition_count",
            "number_of_pages_median",
            "ratings_average",
            "ratings_count",
            "subject",
            "place",
            "time",
            "cover_i",
        ]),
    }

    response = requests.get(url, params=params, timeout=10)
    response.raise_for_status()
    docs = response.json().get("docs", [])

    if not docs:
        return None

    # Pick the result with the highest edition_count as the canonical match
    best = max(docs, key=lambda d: d.get("edition_count", 0))
    return best


def format_result(doc: dict, fallback_pages: int = None) -> dict:
    """
    Flatten an Open Library doc into a clean dict for display.
    
    Includes edge-case handling for page counts:
      - Uses Open Library's `number_of_pages_median`.
      - If the median is missing (None) or an extreme low outlier (< 25 pages,
        such as a teaser/pamphlet), falls back to `fallback_pages` (e.g. from Goodreads).
    """
    subjects = clean_and_prioritize_subjects(
        raw_subjects=doc.get("subject"),
        places=doc.get("place"),
        times=doc.get("time"),
        limit=5,
    )

    # Validate pages_median & protect against low outliers (e.g. 12-page samplers)
    raw_pages = doc.get("number_of_pages_median")
    pages_median = None
    if raw_pages is not None:
        try:
            val = int(raw_pages)
            # If val < 25 and we have a realistic fallback, use fallback
            if val < 25 and fallback_pages and fallback_pages >= 25:
                pages_median = int(fallback_pages)
            else:
                pages_median = val
        except (ValueError, TypeError):
            pages_median = int(fallback_pages) if fallback_pages else None
    elif fallback_pages:
        try:
            pages_median = int(fallback_pages)
        except (ValueError, TypeError):
            pages_median = None

    return {
        "ol_key":             doc.get("key"),
        "ol_title":           doc.get("title"),
        "ol_author":          ", ".join(doc.get("author_name") or []),
        "first_publish_year": doc.get("first_publish_year"),
        "edition_count":      doc.get("edition_count"),
        "pages_median":       pages_median,
        "ratings_average":    round(doc.get("ratings_average") or 0, 2),
        "ratings_count":      doc.get("ratings_count"),
        "cover_id":           doc.get("cover_i"),
        "cover_url":          f"https://covers.openlibrary.org/b/id/{doc['cover_i']}-M.jpg"
                              if doc.get("cover_i") else None,
        "subjects":           ", ".join(subjects),
    }

In [22]:
# ── Test ─────────────────────────────────────────────────────────────────────
test_title  = "happy place"
test_author = "emily henry"

doc = fetch_best_book_match(test_title, test_author)

if doc:
    result = format_result(doc)
    print(f"Best match for '{test_title}' by {test_author}:")
    for k, v in result.items():
        print(f"  {k:<22} {v}")
else:
    print("No match found.")

Best match for 'happy place' by emily henry:
  ol_key                 /works/OL28607665W
  ol_title               Happy Place
  ol_author              Emily Henry
  first_publish_year     2023
  edition_count          9
  pages_median           400
  ratings_average        3.73
  ratings_count          15
  cover_id               13233403
  cover_url              https://covers.openlibrary.org/b/id/13233403-M.jpg
  subjects

---
---

# 📝 Free-Text Book Input Parser

Everything below handles the case where a user **types their books as text** instead of uploading a Goodreads CSV.  
The parser cleans up messy input and outputs a DataFrame that plugs straight into `csv_to_sqlite` above.

### What the parser handles
| Problem the user creates | How we fix it |
|---|---|
| Extra whitespace / blank lines | `.strip()`, skip empty lines |
| Different delimiters (comma, tab, pipe, `" by "`) | Try each delimiter strategy in order |
| Ratings on a 0–10 scale | Divide by 2, clamp to 0–5 |
| Missing ratings | Default to 0 (unrated) |
| Duplicate entries (different casing/spacing) | Deduplicate on lowercase, stripped title+author |
| Stray quotes, bullets, numbering | Regex strips them off |

---
## 🔍 Regex Crash Course — What is it and why do we need it?

**Regex** (Regular Expressions) is a mini-language for describing **text patterns**.  
Instead of searching for an exact word like `"hello"`, you can search for *patterns* like:

> "Find me a number, followed by a slash, followed by another number" → that's a rating like `8/10`

Python gives us the `re` module to use regex. The two main functions we use:

| Function | What it does | Example |
|---|---|---|
| `re.sub(pattern, replacement, text)` | **Find & replace** — finds all matches of `pattern` in `text` and replaces them with `replacement` | `re.sub(r'\s+', ' ', '  too   many   spaces  ')` → `' too many spaces '` |
| `re.search(pattern, text)` | **Find first match** — returns a match object (or `None`) | `re.search(r'\d+', 'rating: 4')` → finds `'4'` |
| `re.match(pattern, text)` | **Match from the start** — like `search` but only at the beginning | `re.match(r'\d+', '4 stars')` → finds `'4'` |

### The building blocks (cheat sheet)

| Symbol | Meaning | Example | Matches |
|---|---|---|---|
| `\d` | Any single digit (0-9) | `\d\d` | `"42"`, `"07"` |
| `\d+` | One or more digits | `\d+` | `"4"`, `"42"`, `"1234"` |
| `\d*` | Zero or more digits | `\d\d*` | `"4"`, `"42"` |
| `\s` | Any whitespace (space, tab, newline) | `\s+` | `"   "`, `"\t"` |
| `\s+` | One or more whitespace chars | `\s+` | collapses `"  "` → `" "` |
| `.` | Any single character | `b.t` | `"bat"`, `"bit"`, `"b3t"` |
| `.+` | One or more of anything | `.+` | `"literally anything"` |
| `.+?` | One or more, but **as few as possible** (lazy) | `.+? by` | Stops at the *first* `" by "` |
| `*` | Zero or more of the previous thing | `\d*` | `""`, `"5"`, `"55"` |
| `+` | One or more of the previous thing | `\d+` | `"5"`, `"55"` (not `""`) |
| `?` | Zero or one (makes something optional) | `\.?` | Matches `"."` or nothing |
| `^` | Start of string | `^The` | `"The ..."` but not `"In The"` |
| `$` | End of string | `\d$` | `"rating 5"` (ends in digit) |
| `[abc]` | Any one of these characters | `[,;]` | Matches `,` or `;` |
| `[^abc]` | Any character EXCEPT these | `[^a-z]` | Matches non-lowercase |
| `(...)` | Capture group — saves what's inside | `(\d+)/(\d+)` | From `"8/10"`: group(1)=`"8"`, group(2)=`"10"` |
| `(?:...)` | Group but DON'T capture | `(?:\s*/\s*\d+)` | Groups without saving |
| `\b` | Word boundary | `\bby\b` | `" by "` but not `"baby"` |

> 💡 **Why `r'...'`?** The `r` before the string means "raw string" — it tells Python not to interpret  
> backslashes as escape characters. Without it, `\d` would confuse Python. With `r'\d'`, Python passes  
> the literal characters `\d` to the regex engine.

### 🧪 Live regex examples — run these to see what each pattern does

In [ ]:
import re

# ── Example 1: \s+ means "one or more whitespace characters" ────────────────
# re.sub REPLACES every match with a single space
messy = '  The    Nightingale   '
clean = re.sub(r'\s+', ' ', messy).strip()
print(f'Before: {messy!r}')
print(f'After:  {clean!r}')
print()
# \s  = any single whitespace character (space, tab, newline)
# \s+ = one or MORE whitespace characters in a row
# So '    ' (4 spaces) is ONE match, replaced by ONE space

In [ ]:
# ── Example 2: \d+ means "one or more digits" ─────────────────────────────────
# re.search FINDS the first match in the string
result = re.search(r'\d+', 'rating: 4 stars')
print(f'Found: {result.group()!r}')   # => '4'

result2 = re.search(r'\d+', 'no numbers here')
print(f'Found: {result2}')              # => None
print()
# \d  = any single digit: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
# \d+ = one or MORE digits in a row, so it matches '4' or '42' or '100'

In [ ]:
# ── Example 3: Capture groups () — extracting parts of a match ─────────────
# Pattern: (one-or-more-digits) / (one-or-more-digits)
rating_text = 'I give it 8/10'
m = re.search(r'(\d+)/(\d+)', rating_text)

if m:
    print(f'Full match:  {m.group()!r}')    # => '8/10'
    print(f'Group 1:     {m.group(1)!r}')   # => '8'   (the numerator)
    print(f'Group 2:     {m.group(2)!r}')   # => '10'  (the denominator)
print()
# The parentheses CREATE GROUPS — each (...) captures what it matches
# group(0) or group() = the entire match
# group(1) = what the FIRST (...) captured
# group(2) = what the SECOND (...) captured

In [ ]:
# ── Example 4: ^ and $ — anchoring to start/end of string ──────────────────
# ^ means "start of string", $ means "end of string"

# Remove leading numbering like "1." or "2)" from the START of a line
lines = ['1. The Nightingale', '2) Lock Every Door', 'Happy Place']

for line in lines:
    cleaned = re.sub(r'^\d+[.)\-]\s*', '', line)
    print(f'{line!r:30s}  =>  {cleaned!r}')
print()
# ^       = only match at the START of the string
# \d+     = one or more digits  (the "1" or "2")
# [.)\-]  = any ONE of these characters: . or ) or -
# \s*     = zero or more whitespace after it

In [ ]:
# ── Example 5: .+? (lazy match) vs .+ (greedy) with "by" ───────────────────
# This is the trickiest one — it's how we split "Title by Author"

line = 'Stand by Me by Stephen King'

# GREEDY (.+) grabs as MUCH as possible before " by "
greedy = re.match(r'^(.+)\s+by\s+(.+)$', line)
print('Greedy match:')
print(f'  Title:  {greedy.group(1)!r}')   # => 'Stand by Me'
print(f'  Author: {greedy.group(2)!r}')   # => 'Stephen King'

# LAZY (.+?) grabs as LITTLE as possible before " by "
lazy = re.match(r'^(.+?)\s+by\s+(.+)$', line)
print('Lazy match:')
print(f'  Title:  {lazy.group(1)!r}')     # => 'Stand'
print(f'  Author: {lazy.group(2)!r}')     # => 'Me by Stephen King'
print()
# We want GREEDY here! It matches the LAST "by" in the string,
# so "Stand by Me" stays together as the title.
# The ? after + makes it LAZY (match as little as possible).
# Without ?, it's GREEDY (match as much as possible).

In [ ]:
# ── Example 6: [^a-z0-9] — removing everything EXCEPT letters & digits ────
# This is how we create deduplication keys

title1 = "The Nightingale"
title2 = "  the   NIGHTINGALE!!  "

key1 = re.sub(r'[^a-z0-9]', '', title1.lower())
key2 = re.sub(r'[^a-z0-9]', '', title2.lower())

print(f'{title1!r:30s}  =>  {key1!r}')
print(f'{title2!r:30s}  =>  {key2!r}')
print(f'Same? {key1 == key2}')   # => True!
print()
# [^a-z0-9] = any character that is NOT a lowercase letter or digit
# The ^ INSIDE [...] means "NOT"
# So re.sub replaces all spaces, punctuation, etc. with nothing (deletes them)
# After .lower(), both titles become 'thenightingale' — duplicates detected!

In [ ]:
# ── Example 7: Putting it together — the rating regex explained ────────────
# This is the actual pattern used in normalize_rating()

pattern = r'(\d+\.?\d*)\s*/\s*(\d+)'
# Let's break it down piece by piece:
#   (         — start capture group 1 (the numerator)
#   \d+       — one or more digits             e.g. "8"
#   \.?       — an optional decimal point       e.g. "8." or "8"
#   \d*       — zero or more digits after it    e.g. "8.5" or "8"
#   )         — end capture group 1
#   \s*       — zero or more spaces
#   /         — a literal slash character
#   \s*       — zero or more spaces
#   (\d+)     — capture group 2: one or more digits (the denominator)

test_cases = ['8/10', '4/5', '7.5 / 10', '3.5/5', 'no rating']

for text in test_cases:
    m = re.search(pattern, text)
    if m:
        print(f'{text!r:15s}  =>  numerator={m.group(1)!r}, denominator={m.group(2)!r}')
    else:
        print(f'{text!r:15s}  =>  no match')

---
## Parser Helper Functions

Now that we understand regex, here are the three helper functions that do the heavy lifting.  
Each one has inline comments explaining *which* regex pattern is used and *why*.

In [ ]:
import re
from typing import List, Dict, Optional

In [ ]:
def clean_field(text: str) -> str:
    """
    Clean a single text field (title or author):
      - Strip leading/trailing whitespace
      - Strip markdown checkbox items: '- [ ]', '* [x]', etc.
      - Remove surrounding quotes, brackets, parentheses
      - Remove leading bullets, dashes, numbering
      - Remove trailing/leading stray dashes
      - Collapse multiple internal spaces to one
      - Title-case the result for consistent display
    """
    if not text or not isinstance(text, str):
        return ""

    s = text.strip()
    s = re.sub(r"^\s*[-*•]?\s*\[\s*[xX ]?\s*\]\s*", "", s)
    s = re.sub(r"^[\[\]\(\)'\"'\"\u201c\u201d\u2018\u2019]+|[\[\]\(\)'\"'\"\u201c\u201d\u2018\u2019]+$", "", s)
    s = re.sub(r"^\s*(?:\d+[.)\-]\s*|[\-•*]\s+)", "", s)
    s = re.sub(r"^[-–—:]+|[-–—:]+$", "", s).strip()
    s = re.sub(r"\s+", " ", s).strip()
    return s.title()


def normalize_rating(raw: str) -> int:
    """
    Parse and normalize a rating value:
      - Extract numeric value from strings like '4', '4/5', '8/10', '4 stars', 'rating: 3'
      - If scale is /10 (either explicit or value > 5), divide by 2
      - Clamp to 0-5 integer range
      - Return 0 if unparseable (treated as 'unrated')
    """
    if not raw or not isinstance(raw, str):
        return 0

    s = raw.strip().lower()
    slash_match = re.search(r'(\d+\.?\d*)\s*/\s*(\d+)', s)
    if slash_match:
        numerator = float(slash_match.group(1))
        denominator = int(slash_match.group(2))
        if denominator == 10:
            value = numerator / 2.0
        elif denominator == 5:
            value = numerator
        else:
            value = (numerator / denominator) * 5.0 if denominator > 0 else 0
        return max(0, min(5, round(value)))

    num_match = re.search(r'(\d+\.?\d*)', s)
    if not num_match:
        return 0

    value = float(num_match.group(1))
    if value > 5:
        value = value / 2.0

    return max(0, min(5, round(value)))


def normalize_for_dedup(title: str, author: str) -> str:
    """
    Create a deduplication key from title + author:
      - Lowercase
      - Remove all non-alphanumeric characters (punctuation, extra spaces)
      - Concatenate title and author
    """
    t = re.sub(r'[^a-z0-9]', '', title.lower())
    a = re.sub(r'[^a-z0-9]', '', author.lower())
    return f"{t}|{a}"

---
## 2. Unit Tests for Helpers

In [ ]:
# ── Test clean_field ──────────────────────────────────────────────────────────
print("=== clean_field tests ===")

tests_clean = [
    ('  "The Nightingale"  ',       'The Nightingale'),
    ("  'kristin hannah'  ",        'Kristin Hannah'),
    ('1. The Nightingale',          'The Nightingale'),
    ('2) Lock Every Door',          'Lock Every Door'),
    ('- Mona\'s Eyes',              "Mona'S Eyes"),       # title() quirk with apostrophe
    ('•  Happy   Place ',           'Happy Place'),
    ('   ',                         ''),
    (None,                          ''),
    ('\u201cHow to Hide an Empire\u201d', 'How To Hide An Empire'),
]

for raw, expected in tests_clean:
    result = clean_field(raw)
    status = '✅' if result == expected else '❌'
    print(f"  {status} clean_field({raw!r:40s}) => {result!r:30s} (expected {expected!r})")

print()

In [ ]:
# ── Test normalize_rating ─────────────────────────────────────────────────────
print("=== normalize_rating tests ===")

tests_rating = [
    ('5',          5),
    ('4',          4),
    ('0',          0),
    ('3.7',        4),    # rounds to nearest int
    ('8/10',       4),    # 8/10 => 4.0
    ('9/10',       4),    # 9/10 => 4.5 => Python banker's rounding => 4
    ('10/10',      5),    # 10/10 => 5.0
    ('4/5',        4),
    ('5/5',        5),
    ('7',          4),    # > 5, so 7/2 = 3.5 => rounds to 4
    ('10',         5),    # > 5, so 10/2 = 5.0
    ('4 stars',    4),
    ('rating: 3',  3),
    ('★★★★',       0),    # no digits => 0
    ('',           0),
    (None,         0),
    ('abc',        0),
    ('-1',         1),    # regex extracts '1' from '-1', result is 1
    ('6',          3),    # > 5, so 6/2 = 3.0
    ('15/10',      5),    # 15/10 => 7.5/2 => no, 15/10 = 7.5... wait: /10 branch => 15/2 = 7.5, clamped to 5
]

for raw, expected in tests_rating:
    result = normalize_rating(raw)
    status = '✅' if result == expected else '❌'
    print(f"  {status} normalize_rating({raw!r:15s}) => {result}  (expected {expected})")

print()

In [ ]:
# ── Test normalize_for_dedup ──────────────────────────────────────────────────
print("=== normalize_for_dedup tests ===")

# These pairs should produce the SAME dedup key
equiv_pairs = [
    (('The Nightingale', 'Kristin Hannah'),
     ('the nightingale', 'kristin hannah')),
    (('  The   Nightingale  ', '  Kristin Hannah  '),
     ('The Nightingale', 'Kristin Hannah')),
    (('Mona\'s Eyes', 'Thomas Schlesser'),
     ('Monas Eyes', 'Thomas Schlesser')),
]

for (t1, a1), (t2, a2) in equiv_pairs:
    k1 = normalize_for_dedup(t1, a1)
    k2 = normalize_for_dedup(t2, a2)
    status = '✅' if k1 == k2 else '❌'
    print(f"  {status} '{t1}' + '{a1}'  ==  '{t2}' + '{a2}'  =>  {k1} == {k2}")

print()

---
## 3. Main Parser: `parse_book_text_input`

In [ ]:
def parse_book_line(line: str) -> Optional[Dict[str, object]]:
    """
    Parse a single line of text into a book dict with keys: Title, Author, My Rating.
    """
    if not line or not isinstance(line, str):
        return None

    s = line.strip()
    if not s:
        return None

    # Remove markdown checkbox markers and list bullets
    s = re.sub(r"^\s*[-*•]?\s*\[\s*[xX ]?\s*\]\s*", "", s).strip()
    s = re.sub(r"^\s*(?:\d+[.)\-]\s*|[•*]\s+)", "", s).strip()

    title = ""
    author = ""
    rating_raw = ""

    # Strategy 1: 'Title by Author'
    by_match = re.match(r"^(.+?)\s+by\s+(.+)$", s, re.IGNORECASE)
    if by_match:
        title_part = by_match.group(1).strip()
        rest = by_match.group(2).strip()

        trailing_rating = re.search(
            r"[,;\-–—|]\s*(\d+\.?\d*(?:\s*/\s*\d+)?(?:\s*stars?)?)\s*$",
            rest,
            re.IGNORECASE
        )
        if trailing_rating:
            rating_raw = trailing_rating.group(1)
            author_part = rest[:trailing_rating.start()].strip()
        else:
            end_rating = re.search(r"\s+(\d+\.?\d*(?:\s*/\s*\d+)?)\s*$", rest)
            if end_rating:
                rating_raw = end_rating.group(1)
                author_part = rest[:end_rating.start()].strip()
            else:
                author_part = rest

        title = clean_field(title_part)
        author = clean_field(author_part)
        rating = normalize_rating(rating_raw)

        if title and author:
            return {"Title": title, "Author": author, "My Rating": rating}

    # Strategy 2: Pipe-separated
    if '|' in s:
        parts = [p.strip() for p in s.split('|') if p.strip()]
        if len(parts) >= 2:
            title = clean_field(parts[0])
            author = clean_field(parts[1])
            rating_raw = parts[2] if len(parts) >= 3 else ""
            rating = normalize_rating(rating_raw)
            if title and author:
                return {"Title": title, "Author": author, "My Rating": rating}

    # Strategy 3: Tab-separated
    if '\t' in s:
        parts = [p.strip() for p in s.split('\t') if p.strip()]
        if len(parts) >= 2:
            title = clean_field(parts[0])
            author = clean_field(parts[1])
            rating_raw = parts[2] if len(parts) >= 3 else ""
            rating = normalize_rating(rating_raw)
            if title and author:
                return {"Title": title, "Author": author, "My Rating": rating}

    # Strategy 4: Comma-separated
    if ',' in s:
        parts = [p.strip() for p in s.split(',') if p.strip()]
        if len(parts) >= 2:
            last = parts[-1].strip()
            if re.match(r'^\d+\.?\d*(?:\s*/\s*\d+)?(?:\s*stars?)?$', last, re.IGNORECASE):
                rating_raw = last
                if len(parts) >= 3:
                    title = clean_field(parts[0])
                    author = clean_field(', '.join(parts[1:-1]))
                else:
                    title = clean_field(parts[0])
                    author = ""
            else:
                title = clean_field(parts[0])
                author = clean_field(', '.join(parts[1:]))
                rating_raw = ""

            rating = normalize_rating(rating_raw)
            if title and author:
                return {"Title": title, "Author": author, "My Rating": rating}

    # Strategy 5: Dash-separated
    if re.search(r'\s+-\s+', s):
        parts = [p.strip() for p in re.split(r'\s+-\s+', s) if p.strip()]
        if len(parts) >= 2:
            title = clean_field(parts[0])
            author = clean_field(parts[1])
            rating_raw = parts[2] if len(parts) >= 3 else ""
            rating = normalize_rating(rating_raw)
            if title and author:
                return {"Title": title, "Author": author, "My Rating": rating}

    return None

---
## 4. Integration Tests — Various Input Formats

In [ ]:
# ── Test 1: "Title by Author, Rating" format ───────────────────────────────────
print("━" * 60)
print("TEST 1: 'Title by Author, Rating' format")
print("━" * 60)

text_by = """
The Nightingale by Kristin Hannah, 5
Mona's Eyes by Thomas Schlesser, 5
Lock Every Door by Riley Sager, 5
Hooked by Asako Yuzuki, 4
Happy Place by Emily Henry, 8/10
Latitudes of Longing by Shubhangi Swarup
"""

df1 = parse_book_text_input(text_by)
print(f"Parsed {len(df1)} books:\n")
df1

In [ ]:
# ── Test 2: Comma-separated format ────────────────────────────────────────────
print("━" * 60)
print("TEST 2: Comma-separated format")
print("━" * 60)

text_csv = """
The Nightingale, Kristin Hannah, 5
Lock Every Door, Riley Sager, 5
Hooked, Asako Yuzuki, 4
One-Star Romance, Laura Hankin
A Guardian and a Thief, Megha Majumdar, 4
"""

df2 = parse_book_text_input(text_csv)
print(f"Parsed {len(df2)} books:\n")
df2

In [ ]:
# ── Test 3: Pipe-separated format ─────────────────────────────────────────────
print("━" * 60)
print("TEST 3: Pipe-separated format")
print("━" * 60)

text_pipe = """
The Nightingale | Kristin Hannah | 5
Mona's Eyes | Thomas Schlesser | 10/10
Lock Every Door | Riley Sager | 4
"""

df3 = parse_book_text_input(text_pipe)
print(f"Parsed {len(df3)} books:\n")
df3

In [ ]:
# ── Test 4: Tab-separated format ──────────────────────────────────────────────
print("━" * 60)
print("TEST 4: Tab-separated format")
print("━" * 60)

text_tab = "The Nightingale\tKristin Hannah\t5\nHooked\tAsako Yuzuki\t4"

df4 = parse_book_text_input(text_tab)
print(f"Parsed {len(df4)} books:\n")
df4

In [ ]:
# ── Test 5: Dash-separated format ─────────────────────────────────────────────
print("━" * 60)
print("TEST 5: Dash-separated format")
print("━" * 60)

text_dash = """
The Nightingale - Kristin Hannah - 5
Lock Every Door - Riley Sager - 5
Hooked - Asako Yuzuki - 4
"""

df5 = parse_book_text_input(text_dash)
print(f"Parsed {len(df5)} books:\n")
df5

In [ ]:
# ── Test 6: Numbered list with bullets ────────────────────────────────────────
print("━" * 60)
print("TEST 6: Numbered / bulleted list")
print("━" * 60)

text_numbered = """
1. The Nightingale by Kristin Hannah, 5
2. Lock Every Door by Riley Sager, 5
3) Hooked by Asako Yuzuki, 4
• Happy Place by Emily Henry, 3
* Latitudes of Longing by Shubhangi Swarup, 3
"""

df6 = parse_book_text_input(text_numbered)
print(f"Parsed {len(df6)} books:\n")
df6

---
## 5. Edge Case Tests

In [ ]:
# ── Test 7: Duplicate removal ─────────────────────────────────────────────────
print("━" * 60)
print("TEST 7: Duplicate removal")
print("━" * 60)

text_dupes = """
The Nightingale by Kristin Hannah, 5
the nightingale by kristin hannah, 5
THE NIGHTINGALE by KRISTIN HANNAH, 5
  The  Nightingale  by  Kristin  Hannah , 5
Lock Every Door by Riley Sager, 5
lock every door by riley sager, 4
"""

df7 = parse_book_text_input(text_dupes)
print(f"Parsed {len(df7)} books (should be 2 — duplicates removed):\n")
df7

In [ ]:
# ── Test 8: Rating edge cases ─────────────────────────────────────────────────
print("━" * 60)
print("TEST 8: Rating normalization edge cases")
print("━" * 60)

text_ratings = """
Book A by Author A, 10/10
Book B by Author B, 7/10
Book C by Author C, 0/5
Book D by Author D, 8
Book E by Author E, 3.7
Book F by Author F
Book G by Author G, 4 stars
Book H by Author H, 6/10
"""

df8 = parse_book_text_input(text_ratings)
print(f"Parsed {len(df8)} books:\n")
print("Expected ratings: 5, 4, 0, 4, 4, 0, 4, 3")
print(f"Actual ratings:   {', '.join(str(r) for r in df8['My Rating'].tolist())}")
print()
df8

In [ ]:
# ── Test 9: Messy whitespace, blank lines, quotes ─────────────────────────────
print("━" * 60)
print("TEST 9: Messy whitespace, blank lines, quotes")
print("━" * 60)

text_messy = """


   "The Nightingale"  ,   "Kristin Hannah"  ,  5

   'Lock Every Door' , 'Riley Sager'  , 5   

    Hooked    ,   Asako  Yuzuki   ,    4


"""

df9 = parse_book_text_input(text_messy)
print(f"Parsed {len(df9)} books (should be 3):\n")
df9

In [ ]:
# ── Test 10: Unparseable lines & header skipping ──────────────────────────────
print("━" * 60)
print("TEST 10: Unparseable lines & header detection")
print("━" * 60)

text_bad = """
Title, Author, Rating
The Nightingale by Kristin Hannah, 5
just some random text with no structure
Lock Every Door by Riley Sager, 5
another line that means nothing
"""

df10 = parse_book_text_input(text_bad)
print(f"Parsed {len(df10)} books (should be 2, with warnings for unparseable lines):\n")
df10

In [ ]:
# ── Test 11: Empty / None input ───────────────────────────────────────────────
print("━" * 60)
print("TEST 11: Empty / None input")
print("━" * 60)

df_empty1 = parse_book_text_input("")
df_empty2 = parse_book_text_input(None)
df_empty3 = parse_book_text_input("   \n\n   \n  ")

print(f"Empty string  => {len(df_empty1)} rows (should be 0)")
print(f"None          => {len(df_empty2)} rows (should be 0)")
print(f"Only blanks   => {len(df_empty3)} rows (should be 0)")

---
## 6. Convert Parsed DataFrame to Goodreads-Compatible Format

This maps the minimal parsed output (`Title`, `Author`, `My Rating`) into the full Goodreads CSV schema so it can flow into the existing `csv_to_sqlite` pipeline seamlessly.

In [ ]:
GOODREADS_COLUMNS = [
    "Book Id", "Title", "Author", "Author l-f", "Additional Authors",
    "ISBN", "ISBN13", "My Rating", "Average Rating", "Publisher",
    "Binding", "Number of Pages", "Year Published", "Original Publication Year",
    "Date Read", "Date Added", "Bookshelves", "Bookshelves with positions",
    "Exclusive Shelf", "My Review", "Spoiler", "Private Notes",
    "Read Count", "Owned Copies",
]


def to_goodreads_df(parsed_df: pd.DataFrame) -> pd.DataFrame:
    """
    Expand a parsed (Title, Author, My Rating) DataFrame into the full
    Goodreads CSV column schema. Missing columns are filled with None.
    
    Also generates:
      - 'Author l-f' in "Last, First" format
      - 'Exclusive Shelf' set to 'read'
      - 'Read Count' set to 1
    """
    if parsed_df.empty:
        return pd.DataFrame(columns=GOODREADS_COLUMNS)

    out = pd.DataFrame(columns=GOODREADS_COLUMNS)
    out["Title"] = parsed_df["Title"]
    out["Author"] = parsed_df["Author"]
    out["My Rating"] = parsed_df["My Rating"]
    out["Exclusive Shelf"] = "read"
    out["Read Count"] = 1
    out["Owned Copies"] = 0

    # Generate "Author l-f" (Last, First) from Author
    def to_last_first(name: str) -> str:
        if not name or not isinstance(name, str):
            return ""
        parts = name.strip().split()
        if len(parts) == 1:
            return parts[0]
        return f"{parts[-1]}, {' '.join(parts[:-1])}"

    out["Author l-f"] = parsed_df["Author"].apply(to_last_first)

    return out


# ── Demo ───────────────────────────────────────────────────────────────────────
print("━" * 60)
print("DEMO: Convert parsed books to Goodreads format")
print("━" * 60)

demo_text = """
The Nightingale by Kristin Hannah, 5
Lock Every Door by Riley Sager, 5
Hooked by Asako Yuzuki, 4
"""

df_parsed = parse_book_text_input(demo_text)
df_goodreads = to_goodreads_df(df_parsed)

print(f"\nGoodreads-format DataFrame ({len(df_goodreads)} rows × {len(df_goodreads.columns)} columns):")
print(f"Columns: {list(df_goodreads.columns)}\n")
df_goodreads[["Title", "Author", "Author l-f", "My Rating", "Exclusive Shelf", "Read Count"]]

---
## 7. Summary of All Tests

In [ ]:
print("\n" + "═" * 60)
print("SUMMARY")
print("═" * 60)

test_results = [
    ("'by' format",         len(df1), 6),
    ("Comma-separated",     len(df2), 5),
    ("Pipe-separated",      len(df3), 3),
    ("Tab-separated",       len(df4), 2),
    ("Dash-separated",      len(df5), 3),
    ("Numbered list",       len(df6), 5),
    ("Duplicate removal",   len(df7), 2),
    ("Rating edge cases",   len(df8), 8),
    ("Messy whitespace",    len(df9), 3),
    ("Unparseable lines",   len(df10), 2),
    ("Empty input",         len(df_empty1), 0),
]

all_pass = True
for name, actual, expected in test_results:
    status = '✅' if actual == expected else '❌'
    if actual != expected:
        all_pass = False
    print(f"  {status} {name:25s}  got {actual} rows  (expected {expected})")

print()
if all_pass:
    print("🎉 All integration tests passed!")
else:
    print("⚠️  Some tests failed — review the output above.")

---
## 8. View Entire `user_catalog` & Database Schema

Inspect the full SQLite `user_catalog` table populated via CSV upload or text parsing.
Use this reference to inspect exact column names, SQLite data types, and record values for writing custom SQL queries.

In [84]:
# ── View Entire user_catalog & Column Information ─────────────────────────────
import sqlite3
import pandas as pd

DB_PATH = 'catalog.db'
TABLE_NAME = 'user_catalog'

conn = sqlite3.connect(DB_PATH)

# 1. Display Schema / Column Info (useful for building SQL queries)
cursor = conn.cursor()
cursor.execute(f"PRAGMA table_info({TABLE_NAME})")
columns_info = cursor.fetchall()

print("═" * 65)
print(f"DATABASE SCHEMA: {TABLE_NAME} in {DB_PATH}")
print("═" * 65)
print(f"{'Col #':<7} {'Column Name':<32} {'SQLite Type':<15}")
print("─" * 65)
for col in columns_info:
    # col: (cid, name, type, notnull, dflt_value, pk)
    print(f"{col[0]:<7} {col[1]:<32} {col[2]:<15}")
print("═" * 65)

# 2. Load and view the entire table
df_catalog = pd.read_sql_query(f"SELECT * FROM {TABLE_NAME}", conn)
conn.close()

print(f"\nTotal Records: {len(df_catalog)} rows × {len(df_catalog.columns)} columns")

# 3. Configure pandas display to show all columns without truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# Display the full catalog DataFrame
df_catalog

═════════════════════════════════════════════════════════════════
DATABASE SCHEMA: user_catalog in catalog.db
═════════════════════════════════════════════════════════════════
Col #   Column Name                      SQLite Type
─────────────────────────────────────────────────────────────────
0       Book Id                          TEXT
1       Title                            TEXT
2       Author                           TEXT
3       Author l-f                       TEXT
4       Additional Authors               TEXT
5       ISBN                             TEXT
6       ISBN13                           TEXT
7       My Rating                        REAL
8       Average Rating                   TEXT
9       Publisher                        TEXT
10      Binding                          TEXT
11      Number of Pages                  REAL
12      Year Published                   TEXT
13      Original Publication Year        REAL
14      Date Read                        TEXT
15      Date Added                       TEXT
16      Bookshelves                      TEXT
17      Bookshelves with positions       TEXT
18      Exclusive Shelf                  TEXT
19      My Review                        TEXT
20      Spoiler                          TEXT
21      Private Notes                    TEXT
22      Read Count                       TEXT
23      Owned Copies                     TEXT
24      ol_key                           TEXT
25      cover_url                        TEXT
26      genres                           TEXT
═════════════════════════════════════════════════════════════════

Total Records: 4 rows × 27 columns

  Book Id                                        Title             Author          Author l-f Additional Authors  ISBN ISBN13  My Rating Average Rating Publisher Binding  Number of Pages Year Published  Original Publication Year Date Read Date Added Bookshelves Bookshelves with positions Exclusive Shelf My Review Spoiler Private Notes Read Count Owned Copies              ol_key                                          cover_url                                             genres
0    None                      Mother Mary Comes to Me      Arundhati Roy      Roy, Arundhati               None  None   None        4.5            4.0      None    None            224.0           None                     2025.0      None       None        None                       None            read      None    None          None       None         None  /works/OL42542753W  https://covers.openlibrary.org/b/id/14981460-M...                                               None
1    None                               City of Djinns  William Dalrymple  Dalrymple, William               None  None   None        4.0           3.67      None    None            351.0           None                     1993.0      None       None        None                       None            read      None    None          None       None         None   /works/OL2322470W     https://covers.openlibrary.org/b/id/4052-M.jpg  history, nonfiction, 15.75 history of asia, in...
2    None       Place: Intimate Encounters with Cities     Ananya Vajpeyi     Vajpeyi, Ananya               None  None   None        4.5           None      None    None              NaN           None                        NaN      None       None        None                       None            read      None    None          None       None         None                None                                               None                                               None
3    None  Chandni Chowk: The Mughal City of Old Delhi      Swapna Liddle      Liddle, Swapna               None  None   None        3.5           None      None    None            176.0           None                     2017.0      None       None        None                       None            read      None    None          None       None         None  /works/OL32465863W                                               None                                            history

In [99]:
# Wrapped Stats SQL queries:
conn = sqlite3.connect('catalog.db')

# Number of books read this year:
sql_query1 = """
SELECT 
    COUNT(DISTINCT Title) as 'Books Read'
FROM user_catalog
"""

query_result1 = pd.read_sql_query(sql_query1, conn)
conn.close()
query_result1

   Books Read
0           4

In [90]:
# Highest rated books this year (returns ALL books tied for the top rating):
conn = sqlite3.connect('catalog.db')
sql_query2 = """
SELECT 
    Title,
    Author,
    [My Rating]
FROM user_catalog
WHERE [My Rating] = (SELECT max([My Rating]) FROM user_catalog)
"""

query_result2 = pd.read_sql_query(sql_query2, conn)
conn.close()
query_result2

                                    Title          Author  My Rating
0                 Mother Mary Comes to Me   Arundhati Roy        4.5
1  Place: Intimate Encounters with Cities  Ananya Vajpeyi        4.5

In [98]:
# Most read genres this year (Top 3):
# We extract the primary genre, ignoring generic 'fiction' if more specific genres exist
# (e.g. prioritizing 'historical fiction', 'fantasy', or 'thriller' over 'fiction').
conn = sqlite3.connect('catalog.db')

sql_query3 = """
WITH SplitGenres AS (
    SELECT 
        Title,
        genres,
        TRIM(SUBSTR(genres, 1, INSTR(genres || ',', ',') - 1)) AS genre_1,
        CASE 
            WHEN INSTR(genres, ',') > 0 THEN 
                TRIM(SUBSTR(
                    SUBSTR(genres, INSTR(genres, ',') + 1), 
                    1, 
                    INSTR(SUBSTR(genres, INSTR(genres, ',') + 1) || ',', ',') - 1
                ))
            ELSE ''
        END AS genre_2,
        CASE 
            WHEN INSTR(SUBSTR(genres, INSTR(genres, ',') + 1), ',') > 0 THEN 
                TRIM(SUBSTR(
                    SUBSTR(SUBSTR(genres, INSTR(genres, ',') + 1), INSTR(SUBSTR(genres, INSTR(genres, ',') + 1), ',') + 1),
                    1,
                    INSTR(SUBSTR(SUBSTR(genres, INSTR(genres, ',') + 1), INSTR(SUBSTR(genres, INSTR(genres, ',') + 1), ',') + 1) || ',', ',') - 1
                ))
            ELSE ''
        END AS genre_3
    FROM user_catalog
    WHERE genres IS NOT NULL AND TRIM(genres) != ''
),
CandidateGenres AS (
    SELECT 
        Title,
        genres,
        CASE 
            WHEN LOWER(genre_1) IN ('fiction', 'general', 'fiction / general') THEN
                CASE 
                    WHEN genre_2 != '' AND LOWER(genre_2) NOT IN ('fiction', 'general', 'fiction / general') THEN genre_2
                    WHEN genre_3 != '' AND LOWER(genre_3) NOT IN ('fiction', 'general', 'fiction / general') THEN genre_3
                    WHEN genre_2 != '' THEN genre_2
                    ELSE genre_1
                END
            ELSE genre_1
        END AS candidate_genre
    FROM SplitGenres
),
PrimaryGenres AS (
    SELECT 
        Title,
        CASE 
            WHEN LOWER(candidate_genre) LIKE 'fiction / %' THEN TRIM(SUBSTR(candidate_genre, 11))
            ELSE candidate_genre
        END AS primary_genre
    FROM CandidateGenres
)
SELECT 
    primary_genre AS Genre,
    COUNT(*) AS [Books Read]
FROM PrimaryGenres
WHERE primary_genre != ''
GROUP BY primary_genre
ORDER BY [Books Read] DESC
LIMIT 3;
"""

query_result3 = pd.read_sql_query(sql_query3, conn)
conn.close()
query_result3

     Genre  Books Read
0  history           2

In [ ]:
# Longest book read this year:
# CAST(... AS INTEGER) strips the decimal, and the subquery handles ties
conn = sqlite3.connect('catalog.db')

sql_query4 = """
SELECT 
    Title,
    Author,
    CAST([Number of Pages] AS INTEGER) AS [Pages]
FROM user_catalog
WHERE [Number of Pages] = (SELECT MAX([Number of Pages]) FROM user_catalog)
"""

query_result4 = pd.read_sql_query(sql_query4, conn)
conn.close()
query_result4

   Longest Book           Title             Author
0         351.0  City of Djinns  William Dalrymple

In [96]:
# Most enjoyed genre this year:
# Ranks genres by average rating, ignoring generic 'fiction' if more specific genres exist,
# and declares the contributing book title(s).
conn = sqlite3.connect('catalog.db')

sql_query5 = """
WITH SplitGenres AS (
    SELECT 
        Title,
        Author,
        [My Rating],
        cover_url,
        genres,
        TRIM(SUBSTR(genres, 1, INSTR(genres || ',', ',') - 1)) AS genre_1,
        CASE 
            WHEN INSTR(genres, ',') > 0 THEN 
                TRIM(SUBSTR(
                    SUBSTR(genres, INSTR(genres, ',') + 1), 
                    1, 
                    INSTR(SUBSTR(genres, INSTR(genres, ',') + 1) || ',', ',') - 1
                ))
            ELSE ''
        END AS genre_2,
        CASE 
            WHEN INSTR(SUBSTR(genres, INSTR(genres, ',') + 1), ',') > 0 THEN 
                TRIM(SUBSTR(
                    SUBSTR(SUBSTR(genres, INSTR(genres, ',') + 1), INSTR(SUBSTR(genres, INSTR(genres, ',') + 1), ',') + 1),
                    1,
                    INSTR(SUBSTR(SUBSTR(genres, INSTR(genres, ',') + 1), INSTR(SUBSTR(genres, INSTR(genres, ',') + 1), ',') + 1) || ',', ',') - 1
                ))
            ELSE ''
        END AS genre_3
    FROM user_catalog
    WHERE genres IS NOT NULL AND TRIM(genres) != '' AND [My Rating] IS NOT NULL
),
CandidateGenres AS (
    SELECT 
        Title,
        Author,
        [My Rating],
        cover_url,
        genres,
        CASE 
            WHEN LOWER(genre_1) IN ('fiction', 'general', 'fiction / general') THEN
                CASE 
                    WHEN genre_2 != '' AND LOWER(genre_2) NOT IN ('fiction', 'general', 'fiction / general') THEN genre_2
                    WHEN genre_3 != '' AND LOWER(genre_3) NOT IN ('fiction', 'general', 'fiction / general') THEN genre_3
                    WHEN genre_2 != '' THEN genre_2
                    ELSE genre_1
                END
            ELSE genre_1
        END AS candidate_genre
    FROM SplitGenres
),
PrimaryGenres AS (
    SELECT 
        Title,
        Author,
        [My Rating],
        cover_url,
        CASE 
            WHEN LOWER(candidate_genre) LIKE 'fiction / %' THEN TRIM(SUBSTR(candidate_genre, 11))
            ELSE candidate_genre
        END AS primary_genre
    FROM CandidateGenres
),
GenreAgg AS (
    SELECT 
        primary_genre AS Genre,
        ROUND(AVG([My Rating]), 2) AS [Average Rating],
        COUNT(*) AS [Books Read],
        MAX(cover_url) AS cover_url
    FROM PrimaryGenres
    WHERE primary_genre != ''
    GROUP BY primary_genre
),
DistinctGenreBooks AS (
    SELECT DISTINCT
        primary_genre,
        Title || CASE WHEN Author IS NOT NULL AND TRIM(Author) != '' THEN ' by ' || Author ELSE '' END AS book_title
    FROM PrimaryGenres
    WHERE primary_genre != ''
)
SELECT 
    g.Genre,
    g.[Average Rating],
    g.[Books Read],
    (SELECT GROUP_CONCAT(b.book_title, ' • ') FROM DistinctGenreBooks b WHERE b.primary_genre = g.Genre) AS [Book Titles],
    g.cover_url,
    DENSE_RANK() OVER (ORDER BY g.[Average Rating] DESC, g.[Books Read] DESC) AS [Overall Rating Rank]
FROM GenreAgg g
ORDER BY [Overall Rating Rank]
LIMIT 3;
"""

query_result5 = pd.read_sql_query(sql_query5, conn)
conn.close()
query_result5

     Genre  Average Rating  Books Read  Overall Rating Rank
0  history            3.75           2                    1

---
# 🎯 So, what's your NextChapter? (Book Recommendation Engine)

Welcome to your personalized **NextChapter recommendation engine**!
Now that we've analyzed your reading year in the Wrapped recap, let's look forward to what you should read next.

### 🧠 How the Scoring System Works
Instead of a black box, your recommendations are ranked using four transparent criteria:
$$\text{Score} = (0.55 \times \text{Subject Fit}) + (0.20 \times \text{Author Bonus}) + (0.15 \times \text{Community Score}) + (0.10 \times \text{Length Fit})$$

1. **Subject Fit (55%)**: Normalized score matching candidate book subjects with themes you rated 4★ and 5★.
2. **Author Bonus (20%)**: Flat 1.0 boost if written by an author you rated 4★ or 5★.
3. **Community Score (15%)**: Open Library average rating (scaled to 1.0) — only applied if the book has 100+ ratings.
4. **Length Fit (10%)**: Measures how closely page count fits into your **sweet spot** (the middle 50% of books you read).

### 🛡️ Smart Filters & Diversity Rules
- **Target Audience / Age Group Filter**: Inspects your anchor books for children's / juvenile tags. For adult readers, children's and middle-grade classics (like *Anne of Green Gables* or *Adventures of Huckleberry Finn*) are automatically filtered out.
- **Diversity Rules**: No more than 2 picks share the same top subject, no more than 2 by the same author, and 1 slot is reserved for high-rated Nonfiction if you enjoyed nonfiction this year.

In [ ]:
# ── Step 1: Extract Taste Profile & Anchor Books ──────────────────────────────
# We load your catalog from SQLite, find your favorite books (Anchor Books: rated >= 4 stars),
# build your author affinity list, score favorite subjects, and detect target audience.
import sqlite3
import pandas as pd

conn = sqlite3.connect('catalog.db')
user_catalog = pd.read_sql_query('SELECT * FROM user_catalog', conn)
conn.close()

# 1. Identify Anchor Books (rated 4.0 or higher)
anchor_books = user_catalog[user_catalog['My Rating'] >= 4.0].copy()
if anchor_books.empty:
    # Fallback to all rated books if no 4+ stars exist
    anchor_books = user_catalog[user_catalog['My Rating'] > 0].copy()

# 2. Build Author Affinity List (authors of books you rated 4+)
affinity_authors = set(
    anchor_books['Author'].dropna().str.strip().str.lower()
)

# 3. Calculate Subject Affinity Scores based on ratings:
# Higher ratings add positive affinity; low ratings (1-2 stars) downweight themes
subject_scores = {}
for _, row in user_catalog.iterrows():
    rating = row.get('My Rating') or 0
    if rating >= 4.5:
        weight = 2.5     # 5-star favorite
    elif rating >= 3.5:
        weight = 1.5     # 4-star solid read
    elif rating >= 2.5:
        weight = 0.2     # 3-star neutral
    else:
        weight = -1.5    # 1-2 star penalty
    
    genres_text = str(row.get('genres') or '')
    tags = [t.strip().lower() for t in genres_text.split(',') if t.strip()]
    for tag in tags:
        subject_scores[tag] = subject_scores.get(tag, 0.0) + weight

# Sort top subjects
top_subjects = sorted(subject_scores.items(), key=lambda x: x[1], reverse=True)

# 4. Check if the user has a 4+ star Nonfiction anchor
nonfiction_keywords = {
    'nonfiction', 'history', 'biography', 'memoir', 'philosophy',
    'psychology', 'science', 'politics', 'religion', 'christianity'
}
has_nonfiction_anchor = False
for _, row in anchor_books.iterrows():
    row_tags = [t.strip().lower() for t in str(row.get('genres') or '').split(',')]
    if any(any(k in t for k in nonfiction_keywords) for t in row_tags):
        has_nonfiction_anchor = True
        break

# 5. Target Audience / Age Group Check:
# We inspect anchor books for children's / juvenile tags.
# If the user doesn't read children's books, we target Adult readers and filter out juvenile/kids classics.
CHILDREN_KEYWORDS = ('juvenile', "children's", 'child and youth', 'middle grade', 'picture book', 'elementary', 'fairy tale')
reads_children_books = any(
    any(k in str(row.get('genres') or '').lower() for k in CHILDREN_KEYWORDS)
    for _, row in anchor_books.iterrows()
)
ALLOW_JUVENILE = reads_children_books  # Toggle: False ensures adult recommendations only

print("=" * 60)
print(f"📖 Found {len(anchor_books)} Anchor Books (Rated 4+ stars):")
for _, r in anchor_books[['Title', 'Author', 'My Rating']].iterrows():
    print(f"   ★ {r['My Rating']} - {r['Title']} by {r['Author']}")

print(f"\n✍️ Author Affinity List ({len(affinity_authors)} authors):")
print(f"   {', '.join(sorted([a.title() for a in affinity_authors]))}")

print("\n🏷️ Top 5 Subject Affinities:")
for s, score in top_subjects[:5]:
    print(f"   • {s.title()}: +{score:.1f} pts")

print(f"\n📚 Nonfiction Anchor Detected: {'Yes (Nonfiction slot will be reserved)' if has_nonfiction_anchor else 'No'}")
print(f"🎯 Target Audience: {'All Ages / Juvenile' if ALLOW_JUVENILE else 'General Adult (Filtering out Juvenile & Children classics)'}")
print("=" * 60)

In [ ]:
# ── Step 2: Calculate the "Page Count Sweet Spot" ──────────────────────────────
# We examine the page counts of your anchor books.
# If you have at least 4 anchor books with known page counts, we calculate the middle
# 25th to 75th percentile range. Otherwise, we default to a standard 300 - 500 pages.
import numpy as np

# Extract valid page counts from anchor books
valid_pages = anchor_books['Number of Pages'].dropna().astype(float).tolist()
# Filter out extreme outliers (e.g. 0 pages)
valid_pages = [p for p in valid_pages if p >= 25]

if len(valid_pages) >= 4:
    # 25th percentile (lower boundary) and 75th percentile (upper boundary)
    p25 = float(np.percentile(valid_pages, 25))
    p75 = float(np.percentile(valid_pages, 75))
    sweet_spot_method = f"Calculated from your {len(valid_pages)} favorite reads (25th - 75th percentile)"
else:
    # Default fallback when few books have recorded page counts
    p25, p75 = 300.0, 500.0
    sweet_spot_method = f"Default fallback (needed at least 4 anchor books, found {len(valid_pages)})"

print("=" * 60)
print("📏 YOUR READING LENGTH SWEET SPOT")
print(f"   Ideal Range: {int(p25)} to {int(p75)} pages")
print(f"   Source: {sweet_spot_method}")
print("=" * 60)


# ── The Length Fit Function ───────────────────────────────────────────────────
def calculate_length_fit(pages: float, lower: float = p25, upper: float = p75) -> float:
    """
    Returns 1.0 if inside your sweet spot [lower, upper].
    Smoothly falls off towards 0.0 as distance increases outside the window.
    """
    if pages is None or pd.isna(pages) or pages <= 0:
        return 0.5  # Neutral default if page count is missing
    
    pages = float(pages)
    if lower <= pages <= upper:
        return 1.0
    elif pages < lower:
        # Falls off proportionally as it gets shorter
        return max(0.0, 1.0 - ((lower - pages) / lower))
    else:
        # Falls off proportionally as it gets longer
        return max(0.0, 1.0 - ((pages - upper) / upper))

# Test demonstration:
print("\nDemonstration of length fit across different book sizes:")
test_samples = [150, 250, int(p25), int((p25 + p75) / 2), int(p75), 650, 900]
for p in test_samples:
    fit_score = calculate_length_fit(p, p25, p75)
    print(f"   • {p:>3} pages -> Length Fit Score: {fit_score:.2f} {'(In Sweet Spot!)' if fit_score == 1.0 else ''}")

In [ ]:
# ── Step 3: Source Candidate Books from Open Library ──────────────────────────
# We query Open Library's Search API to discover popular books among active readers
# in your favorite subjects, works by your favorite authors, and top nonfiction if needed.
import requests
import re

def is_children_book(subjects):
    """Return True if any subject tag indicates a juvenile/children's book."""
    if not subjects:
        return False
    juvenile_terms = (
        'juvenile', "children's", 'child and youth',
        'middle grade', 'picture book', 'elementary school', 'early reader'
    )
    for s in subjects:
        s_lower = str(s).lower()
        if any(term in s_lower for term in juvenile_terms):
            return True
    return False

def clean_title(title):
    """Normalize title by stripping subtitle and edition noise (e.g. ' - Export Edition')."""
    if not title:
        return ''
    return re.split(r' - | \(|: ', title)[0].strip().lower()

def get_candidates_from_open_library(top_subj_list, top_author_list, need_nonfiction=False, allow_juvenile=False):
    """Fetch candidate books from Open Library, filtering out read books and children's titles."""
    read_cleaned_titles = set(clean_title(t) for t in user_catalog['Title'].dropna())
    
    candidates = []
    seen_titles = set(read_cleaned_titles)
    headers = {'User-Agent': 'NextChapterBookApp/1.0 (educational research)'}
    
    # 1. Fetch top books for your top 3 specific subjects (excluding generic tags)
    generic_tags = {'fiction', 'general', 'fiction / general', 'nonfiction'}
    filtered_subjects = [s for s, sc in top_subj_list if s.lower() not in generic_tags][:3]
    if not filtered_subjects:
        filtered_subjects = [s for s, sc in top_subj_list][:2]
        
    for subj in filtered_subjects:
        print(f"🔍 Searching Open Library for trending adult books in subject: '{subj}'...")
        url = "https://openlibrary.org/search.json"
        params = {
            "q": f'subject:"{subj}" language:eng',
            "sort": "readinglog",  # Sort by active reader engagement rather than 1800s print counts
            "limit": 15,
            "fields": "key,title,author_name,number_of_pages_median,ratings_average,ratings_count,subject,cover_i"
        }
        try:
            resp = requests.get(url, params=params, headers=headers, timeout=10)
            if resp.status_code == 200:
                for doc in resp.json().get('docs', []):
                    t = doc.get('title')
                    c_title = clean_title(t)
                    if not c_title or c_title in seen_titles:
                        continue
                    # Age group / target audience filter
                    if not allow_juvenile and is_children_book(doc.get('subject', [])):
                        continue
                    seen_titles.add(c_title)
                    doc['is_nonfiction'] = False
                    candidates.append(doc)
        except Exception as e:
            print(f"   ⚠️ Could not fetch for {subj}: {e}")

    # 2. Fetch other books by your affinity authors
    for auth in list(top_author_list)[:2]:
        print(f"🔍 Searching Open Library for books by favorite author: '{auth.title()}'...")
        url = "https://openlibrary.org/search.json"
        params = {
            "author": auth,
            "sort": "readinglog",
            "limit": 6,
            "fields": "key,title,author_name,number_of_pages_median,ratings_average,ratings_count,subject,cover_i"
        }
        try:
            resp = requests.get(url, params=params, headers=headers, timeout=10)
            if resp.status_code == 200:
                for doc in resp.json().get('docs', []):
                    t = doc.get('title')
                    c_title = clean_title(t)
                    if not c_title or c_title in seen_titles:
                        continue
                    if not allow_juvenile and is_children_book(doc.get('subject', [])):
                        continue
                    seen_titles.add(c_title)
                    doc['is_nonfiction'] = False
                    candidates.append(doc)
        except Exception as e:
            print(f"   ⚠️ Could not fetch for {auth}: {e}")

    # 3. If user loved a 4+ nonfiction book, fetch memoirs and history
    if need_nonfiction:
        print("🔍 Searching Open Library for popular Nonfiction candidates...")
        url = "https://openlibrary.org/search.json"
        params = {
            "q": 'subject:memoir OR subject:history language:eng',
            "sort": "readinglog",
            "limit": 10,
            "fields": "key,title,author_name,number_of_pages_median,ratings_average,ratings_count,subject,cover_i"
        }
        try:
            resp = requests.get(url, params=params, headers=headers, timeout=10)
            if resp.status_code == 200:
                for doc in resp.json().get('docs', []):
                    t = doc.get('title')
                    c_title = clean_title(t)
                    if not c_title or c_title in seen_titles:
                        continue
                    if not allow_juvenile and is_children_book(doc.get('subject', [])):
                        continue
                    seen_titles.add(c_title)
                    doc['is_nonfiction'] = True
                    candidates.append(doc)
        except Exception as e:
            print(f"   ⚠️ Could not fetch nonfiction: {e}")

    return candidates

# Run candidate harvester with audience filtering:
candidate_docs = get_candidates_from_open_library(
    top_subjects, 
    affinity_authors, 
    need_nonfiction=has_nonfiction_anchor,
    allow_juvenile=ALLOW_JUVENILE
)

print(f"\n✅ Total adult candidates collected: {len(candidate_docs)}")

In [ ]:
# ── Step 4: Calculate the 4 Terms & Taste Match % ─────────────────────────────
# Formula:
# Score = 0.55 * subject_fit + 0.20 * author_bonus + 0.15 * community + 0.10 * length_fit

# Pre-calculate raw subject scores for all candidates to min-max normalize
raw_subject_scores = []
for doc in candidate_docs:
    tags = [str(s).lower() for s in doc.get('subject', [])]
    raw = sum(subject_scores.get(t, 0.0) for t in tags)
    raw_subject_scores.append(raw)

min_raw = min(raw_subject_scores) if raw_subject_scores else 0.0
max_raw = max(raw_subject_scores) if raw_subject_scores else 1.0
raw_spread = (max_raw - min_raw) if (max_raw - min_raw) > 0 else 1.0

scored_candidates = []

for i, doc in enumerate(candidate_docs):
    # Double check audience safety
    if not ALLOW_JUVENILE and is_children_book(doc.get('subject', [])):
        continue

    title = doc.get('title', 'Unknown Title')
    authors = doc.get('author_name', ['Unknown Author'])
    author = authors[0] if authors else 'Unknown Author'
    pages = doc.get('number_of_pages_median')
    ratings_avg = doc.get('ratings_average') or 0.0
    ratings_cnt = doc.get('ratings_count') or 0
    subjects = doc.get('subject', [])
    cover_i = doc.get('cover_i')
    cover_url = f"https://covers.openlibrary.org/b/id/{cover_i}-M.jpg" if cover_i else None
    is_nonfiction = doc.get('is_nonfiction', False)

    # 1. Subject Fit (0.0 to 1.0) - Normalized overlap with user's top tags
    subject_fit = max(0.0, min(1.0, (raw_subject_scores[i] - min_raw) / raw_spread))

    # 2. Author Bonus (1.0 if author is in your 4+ affinity list, else 0.0)
    author_bonus = 1.0 if any(a.lower() in affinity_authors for a in authors) else 0.0

    # 3. Community Score (rating / 5.0 only if >= 100 ratings, else 0.0)
    if ratings_cnt >= 100:
        community = min(1.0, float(ratings_avg) / 5.0)
    else:
        community = 0.0

    # 4. Length Fit (1.0 inside your sweet spot, falling off outside)
    length_fit = calculate_length_fit(pages, p25, p75)

    # Composite Score (0.0 to 1.0)
    final_score = (
        (0.55 * subject_fit) +
        (0.20 * author_bonus) +
        (0.15 * community) +
        (0.10 * length_fit)
    )

    scored_candidates.append({
        'title': title,
        'author': author,
        'pages': pages,
        'ratings_avg': round(ratings_avg, 2),
        'ratings_cnt': ratings_cnt,
        'subjects': subjects,
        'cover_url': cover_url,
        'is_nonfiction': is_nonfiction,
        'subject_fit': round(subject_fit, 3),
        'author_bonus': round(author_bonus, 2),
        'community': round(community, 3),
        'length_fit': round(length_fit, 3),
        'score': round(final_score, 4),
    })

# Compute Taste Match %:
# Relative percentage compared to the top candidate's score in this run
best_score = max(c['score'] for c in scored_candidates) if scored_candidates else 1.0
for c in scored_candidates:
    c['taste_match'] = round((c['score'] / best_score) * 100, 1)

# Sort candidates descending by score
scored_candidates.sort(key=lambda x: x['score'], reverse=True)

# Display top 8 candidates before diversity filtering
df_scored = pd.DataFrame(scored_candidates)
cols_to_show = ['title', 'author', 'taste_match', 'score', 'subject_fit', 'author_bonus', 'community', 'length_fit', 'pages']
print("=" * 90)
print("📊 TOP SCORED ADULT CANDIDATES (Before Diversity Filtering):")
print("=" * 90)
print(df_scored[cols_to_show].head(8).to_string(index=False))

In [ ]:
# ── Step 5: Apply Diversity Rules & Pick Initial 5 Books (Batch 1) ───────────
# We define a reusable function that picks up to 5 diverse recommendations from our scored candidates.
# Crucially, it accepts an `exclude_titles` parameter so that when we click "Refresh",
# it can skip previously shown books and give us the NEXT 5 best matches!

def select_diverse_recommendations(scored_pool, exclude_titles=None, max_picks=5, reserve_nonfiction=True):
    """
    Greedily select up to `max_picks` books obeying diversity rules:
    - Excludes any titles in `exclude_titles` (used for pagination & refresh).
    - At most 2 books sharing the same primary subject.
    - At most 2 books by the same author.
    - If user has a 4+ nonfiction anchor, reserves 1 slot for the top nonfiction book.
    """
    if exclude_titles is None:
        exclude_titles = set()

    picks = []
    subject_counts = {}
    author_counts = {}

    def get_primary_subject(candidate):
        tags = [str(s).lower() for s in candidate.get('subjects', [])]
        specific = [t for t in tags if t not in ('fiction', 'general', 'fiction / general', 'nonfiction')]
        return specific[0] if specific else (tags[0] if tags else 'general')

    # 1. Nonfiction Slot Reservation (if user loved a 4+ nonfiction read and not yet picked)
    if reserve_nonfiction and has_nonfiction_anchor:
        for cand in scored_pool:
            if cand.get('is_nonfiction', False):
                c_title = clean_title(cand['title'])
                if c_title in exclude_titles:
                    continue
                cand_copy = dict(cand)
                cand_copy['pick_reason'] = "Curated Nonfiction Anchor Pick"
                picks.append(cand_copy)
                top_s = get_primary_subject(cand)
                auth = cand['author'].lower()
                subject_counts[top_s] = 1
                author_counts[auth] = 1
                break

    # 2. Greedy selection for remaining slots
    for cand in scored_pool:
        if len(picks) >= max_picks:
            break

        c_title = clean_title(cand['title'])
        # Skip if already in exclude list or already picked in this batch
        if c_title in exclude_titles or any(clean_title(p['title']) == c_title for p in picks):
            continue

        top_s = get_primary_subject(cand)
        auth = cand['author'].lower()

        # Diversity Rule 1: Max 2 per top subject
        if subject_counts.get(top_s, 0) >= 2:
            continue

        # Diversity Rule 2: Max 2 by the same author
        if author_counts.get(auth, 0) >= 2:
            continue

        # Build personalized reason string
        reasons = []
        if cand['author_bonus'] == 1.0:
            reasons.append(f"Loved author ({cand['author']})")
        if cand['length_fit'] == 1.0 and cand['pages']:
            reasons.append(f"In your sweet spot ({int(cand['pages'])} pages)")
        if cand['subject_fit'] >= 0.7:
            reasons.append(f"High genre match ({top_s.title()})")
        if not reasons:
            reasons.append("High overall taste & community rating")

        cand_copy = dict(cand)
        cand_copy['pick_reason'] = " • ".join(reasons)
        picks.append(cand_copy)

        subject_counts[top_s] = subject_counts.get(top_s, 0) + 1
        author_counts[auth] = author_counts.get(auth, 0) + 1

    return picks

# Generate Batch 1 (Initial recommendations, no exclusions)
batch_1_picks = select_diverse_recommendations(
    scored_candidates, 
    exclude_titles=set(), 
    max_picks=5,
    reserve_nonfiction=True
)

print("=" * 60)
print(f"🎉 BATCH 1 SELECTED ({len(batch_1_picks)} Books):")
print("=" * 60)
for idx, b in enumerate(batch_1_picks, 1):
    print(f"#{idx}. {b['title']} by {b['author']} | Taste Match: {b['taste_match']}%")

In [ ]:
# ── Step 6: Visual Showcase: Batch 1 Shelf ────────────────────────────────────
# Display formatted presentation showing the initial top 5 recommendations.
from IPython.display import display, HTML

print("=" * 70)
print("📚 YOUR NEXTCHAPTER PICKS (BATCH 1)")
print("=" * 70)

for idx, book in enumerate(batch_1_picks, 1):
    pages_display = f"{int(book['pages'])} pages" if book['pages'] else "Page count N/A"
    comm_display = f"★ {book['ratings_avg']} ({book['ratings_cnt']} reviews)" if book['ratings_cnt'] >= 100 else "Rating pending"
    
    print(f"\n#{idx}. {book['title']}")
    print(f"    Author:        {book['author']}")
    print(f"    Taste Match:   🎯 {book['taste_match']}%")
    print(f"    Length:        📖 {pages_display}")
    print(f"    Community:     🌐 {comm_display}")
    print(f"    Why for you:   💡 {book['pick_reason']}")

cards_html = """
<div style="display: flex; flex-wrap: wrap; gap: 16px; margin-top: 15px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
"""
for idx, b in enumerate(batch_1_picks, 1):
    cover_img = f'<img src="{b["cover_url"]}" style="width: 95px; height: 145px; object-fit: cover; border-radius: 6px; box-shadow: 0 4px 10px rgba(0,0,0,0.25);" />' if b.get('cover_url') else '<div style="width: 95px; height: 145px; background: #2a2a32; color: #aaa; display: flex; align-items: center; justify-content: center; border-radius: 6px; font-size: 11px; text-align: center;">No Cover</div>'
    cards_html += f"""
    <div style="background: #181820; color: #ffffff; border: 1px solid #2e2e38; border-radius: 14px; padding: 16px; width: 280px; box-shadow: 0 6px 16px rgba(0,0,0,0.2); display: flex; flex-direction: column; justify-content: space-between;">
        <div style="display: flex; gap: 12px;">
            {cover_img}
            <div style="flex: 1;">
                <div style="background: #2563EB; color: #ffffff; font-size: 10px; font-weight: 700; padding: 3px 8px; border-radius: 999px; display: inline-block; margin-bottom: 6px;">
                    {b['taste_match']}% MATCH
                </div>
                <div style="font-size: 14px; font-weight: 700; line-height: 1.25; margin-bottom: 4px; color: #ffffff;">{b['title']}</div>
                <div style="font-size: 12px; opacity: 0.8; color: #e2e8f0;">by {b['author']}</div>
                <div style="font-size: 11px; opacity: 0.7; margin-top: 6px; color: #cbd5e1;">📖 {int(b['pages']) if b['pages'] else 'N/A'} pages</div>
                <div style="font-size: 11px; color: #fbbf24; margin-top: 2px;">★ {b['ratings_avg']}</div>
            </div>
        </div>
        <div style="margin-top: 12px; padding-top: 8px; border-top: 1px solid rgba(255,255,255,0.1); font-size: 11px; opacity: 0.85; font-style: italic; color: #93c5fd;">
            💡 {b['pick_reason']}
        </div>
    </div>
    """
cards_html += "</div>"

display(HTML(cards_html))

---
### 🔄 Step 7: How the "1-Time Refresh" Mechanism Works

#### 1. Why Did "Refresh" Return the Same Books Previously?
The recommendation engine is **deterministic**:
- Given your reading taste profile, the formula calculates exact mathematical scores for every candidate book.
- When we ask for the top 5, it takes ranks **#1 to #5**.
- If you run the code again without changing anything, rank #1 to #5 are still the exact same books!

#### 2. How the "Next Best Picks" Pagination Works:
Instead of re-querying Open Library or adding random noise:
1. **Track Previously Shown Titles**: We collect the titles from Batch 1 into a `seen_recommendation_titles` set.
2. **Exclude & Advance**: When the user clicks **Refresh**, we instruct `select_diverse_recommendations` to **skip** any book in `seen_recommendation_titles`.
3. **Surface Ranks #6 to #10**: The algorithm automatically selects the next 5 highest-ranking books that still satisfy our genre and author diversity rules.

#### 3. Why Limit to Exactly 1 Refresh?
- **Quality Preservation**: The top 10 books in your candidate pool have the strongest Taste Match % (often 80%+). Allowing infinite refreshes would eventually force the engine down to low-scoring or marginal matches.
- **Decision Clarity**: Having Batch 1 (Primary Picks) and Batch 2 (Alternative Picks) gives the user 10 top-tier choices without inducing decision paralysis.
- **Guardrail**: We enforce `MAX_REFRESHES = 1`. If the user attempts to refresh again, the system informs them that the refresh limit has been reached.

In [ ]:
# ── Step 7: Execute the 1-Time Refresh ─────────────────────────────────────────
# Here we simulate clicking the "🔄 Refresh Recommendations" button.
# We track how many times refresh has been used (`refresh_count`) and enforce `MAX_REFRESHES = 1`.

refresh_count = 0
MAX_REFRESHES = 1

def handle_refresh_click(scored_pool, previous_picks, current_refreshes, max_allowed=1):
    """Simulate clicking the refresh button with 1-time limit enforcement."""
    if current_refreshes >= max_allowed:
        print(f"⚠️ Refresh limit reached ({current_refreshes}/{max_allowed} refreshes used).")
        print("   Showing your current batch. Reset table or re-enrich if you want a fresh profile.")
        return None, current_refreshes

    # 1. Gather all titles shown in previous batches
    seen_titles = {clean_title(b['title']) for b in previous_picks}

    # 2. Select the next 5 highest-scoring diverse recommendations
    next_batch = select_diverse_recommendations(
        scored_pool, 
        exclude_titles=seen_titles, 
        max_picks=5,
        reserve_nonfiction=False  # Nonfiction was already introduced in Batch 1
    )

    new_count = current_refreshes + 1
    print(f"✅ Refresh #{new_count} successful! Sourced next {len(next_batch)} diverse recommendations.")
    return next_batch, new_count

# ── 1. First Refresh (Allowed) ────────────────────────────────────────────────
batch_2_picks, refresh_count = handle_refresh_click(
    scored_candidates, 
    previous_picks=batch_1_picks, 
    current_refreshes=refresh_count, 
    max_allowed=MAX_REFRESHES
)

print("\n" + "=" * 70)
print(f"📚 YOUR REFRESHED NEXTCHAPTER PICKS (BATCH 2 — Picks 6 to 10)")
print("=" * 70)

for idx, book in enumerate(batch_2_picks, 6):
    pages_display = f"{int(book['pages'])} pages" if book['pages'] else "Page count N/A"
    comm_display = f"★ {book['ratings_avg']} ({book['ratings_cnt']} reviews)" if book['ratings_cnt'] >= 100 else "Rating pending"
    
    print(f"\n#{idx}. {book['title']}")
    print(f"    Author:        {book['author']}")
    print(f"    Taste Match:   🎯 {book['taste_match']}%")
    print(f"    Length:        📖 {pages_display}")
    print(f"    Community:     🌐 {comm_display}")
    print(f"    Why for you:   💡 {book['pick_reason']}")

# Rich HTML card view for Batch 2:
cards_html = """
<div style="display: flex; flex-wrap: wrap; gap: 16px; margin-top: 15px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
"""
for idx, b in enumerate(batch_2_picks, 6):
    cover_img = f'<img src="{b["cover_url"]}" style="width: 95px; height: 145px; object-fit: cover; border-radius: 6px; box-shadow: 0 4px 10px rgba(0,0,0,0.25);" />' if b.get('cover_url') else '<div style="width: 95px; height: 145px; background: #2a2a32; color: #aaa; display: flex; align-items: center; justify-content: center; border-radius: 6px; font-size: 11px; text-align: center;">No Cover</div>'
    cards_html += f"""
    <div style="background: #181820; color: #ffffff; border: 1px solid #2e2e38; border-radius: 14px; padding: 16px; width: 280px; box-shadow: 0 6px 16px rgba(0,0,0,0.2); display: flex; flex-direction: column; justify-content: space-between;">
        <div style="display: flex; gap: 12px;">
            {cover_img}
            <div style="flex: 1;">
                <div style="background: #7C3AED; color: #ffffff; font-size: 10px; font-weight: 700; padding: 3px 8px; border-radius: 999px; display: inline-block; margin-bottom: 6px;">
                    {b['taste_match']}% MATCH (REFRESHED)
                </div>
                <div style="font-size: 14px; font-weight: 700; line-height: 1.25; margin-bottom: 4px; color: #ffffff;">{b['title']}</div>
                <div style="font-size: 12px; opacity: 0.8; color: #e2e8f0;">by {b['author']}</div>
                <div style="font-size: 11px; opacity: 0.7; margin-top: 6px; color: #cbd5e1;">📖 {int(b['pages']) if b['pages'] else 'N/A'} pages</div>
                <div style="font-size: 11px; color: #fbbf24; margin-top: 2px;">★ {b['ratings_avg']}</div>
            </div>
        </div>
        <div style="margin-top: 12px; padding-top: 8px; border-top: 1px solid rgba(255,255,255,0.1); font-size: 11px; opacity: 0.85; font-style: italic; color: #c4b5fd;">
            💡 {b['pick_reason']}
        </div>
    </div>
    """
cards_html += "</div>"

display(HTML(cards_html))

# ── 2. Testing the 1-Time Limit (Blocked Attempt) ──────────────────────────────
print("\n" + "-" * 70)
print("🧪 TESTING REFRESH LIMIT: What happens if user clicks 'Refresh' again?")
print("-" * 70)
blocked_batch, refresh_count = handle_refresh_click(
    scored_candidates, 
    previous_picks=batch_2_picks, 
    current_refreshes=refresh_count, 
    max_allowed=MAX_REFRESHES
)